# Global 全局配置
site_analytics: ''
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: '/favicon.ico'
snow: false
click_animate_js: 'candy'
enable_dark: true
highlight_theme: night-eighties # 代码高亮主题（light | night | night-eighties | night-blue | night-bright）
cdn: false # 请注意这里是静态资源的 CDN 来源，图片的 CDN 在下方 jsconfig.main.pic.CDN 段配置
check_update: true

# 自定义样式
customStyles:
  images: # 图片相关设置
    banner: /images/banner.webp # 站点横幅
    background: /images/bg.webp # 站点背景

# Index 首页配置
index:
  post_type: false
  read_count: true
  comment_count: true

# Top Menu 顶部导航栏配置 （具体格式请参照文档）
menu:
  index: /
  archives: /archives/
  friends: /friends/
  about: /about/
  sites:
    submenu: true
    ob: https://openbsd-zh-association.github.io/docs-openbsd-zh/
    nix: https://github.com/nixos-cn
    ruzh: https://ruzhtw.top/
    fedora: https://fedora.fun/
    mtf: https://mtf.saeziae.net

label:
  index: <i class="fa fa-home"></i>首页
  archives: <i class="fa fa-file"></i>档案馆
  friends: <i class="fa fa-paw"></i>好伙伴
  about: <i class="fa fa-heart"></i>关于我
  sites:
    ob: OpenBSD-ZH
    nix: NixOS-CN
    ruzh: 茶楼实验室
    fedora: "Fedora Fün"
    mtf: "MtF Wiki"
    submenu: <i class="fa fa-link"></i>友站
    author: 作者博客
    project: 项目链接

# Footer 页脚配置
group_link: 
contact:
  weibo: 
  mail: 
  telegram: openbsd_zh
  twitter: 
  facebook: 
  linkedin: 
  #fediverse:
    #instance: nya.one
    #username: Candinya
  github: YisuiDenghua
  rss:
timenotice: 本站已运行
icp: 
psr:
  
# Post Page 文章页配置
posts:
  show_cc: true
  donate: false
  share: true
  comments: 
    provider: 'gitalk'
    enableBGImage: false

# Disqus [Disqus](https://disqus.com) 评论相关
disqus:
  shortname: 

# DisqusJS [DisqusJS](https://disqusjs.skk.moe/) 评论相关
disqusjs:
  shortname: 
  sitename: 
  api: 
  apikey: 
  admin: 
  adminlabel: 

# Valine [Valine](https://valine.js.org) 评论相关
valine:
  app_id: 
  app_key: 
  visitor: true
  enableQQ: false

# Twikoo [Twikoo](https://twikoo.js.org) 评论相关
twikoo:
  env_id: 

# Waline [Waline](https://waline.js.org) 评论相关
## 不仅限于以下内容，您可以参照 Waline的 [前端配置文档](https://waline.js.org/reference/client.html) 设置您需要的配置项
## el 和 path 会在页面自动生成，不必加入
waline:
  serverURL: #后端服务器地址，必填
  visitor: true

# Gitalk [Gitalk](https://gitalk.github.io/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitalk 文档](https://github.com/gitalk/gitalk/blob/master/readme-cn.md#%E8%AE%BE%E7%BD%AE) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitalk:
  clientID: '3bce9ab86e2e99797c0f'
  clientSecret: '8c1f41fd72d5a8d13852bbfde9dd862c21c1f9e5'
  repo: 'milena-blog'
  owner: 'YisuiDenghua'
  admin: 
    - 'YisuiDenghua'
  distractionFreeMode: false

# Gitment [Gitment](https://github.com/imsun/gitment/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitment 文档](https://github.com/imsun/gitment#methods) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitment:
  owner: 'YisuiDenghua'
  repo: 'milena-blog'
  oauth:
    client_id: 'Your client ID'
    client_secret: 'Your client secret'

# LiveRe [LiveRe](https://livere.com/) 评论相关
livere:
  id: city
  uid:

# APlayer 左下角音乐播放器
aplayer:
  enabled: true
  playlist: 
  meting:
    server: netease
    type: playlist
    id: 3204190542
  order: random

# Widgets 侧边栏小挂件
sidebar: right
widgets:
- about
- splitter
- toc
- category
- tagcloud
- posts
avatarUri: /images/logo.png #以后可以随时改ww
mobile_toc:
  hide: false
  hide_id: false

# Fancybox 文章内图片单击放大
fancybox: true

# Search 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript 相关配置
## 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    pic:
      CDN: true # 表示使用 CDN 加载图片
      random_amount: 20 # 表示从1~20
      filename: "images/thumb/thumb_{no}.webp" # 相对于主题根目录，表示文件名的格式, {no} 用以指代随机的编号。
                                              # 如果包含 // 表示使用指定域名的绝对路径（例如第三方图床服务等），那么会忽略 CDN 选项
    createTime: "2022/6/19 09:04:33"
    donateBtn: "支持我~"
    scanNotice: "扫一扫，好不好？"
    qr_alipay: "/images/alipayqr.webp"
    qr_wechat: "/images/wechatpayqr.webp"
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}哦哟，崩溃啦~"
    returnTitle: "(*´∇｀*)欸，又好啦~"
    copyrightNotice: "该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"
    expire_day: 30
    topNavScrollToggle: true

# Site verify 站点验证相关配置内容
site_verify:
  google: 
  baidu: 
  bing: 

# Friends 友链相关内容
friends:
  list:
  - name: 马保国
    avatar: "https://avatars.githubusercontent.com/u/96376395"
    link: "https://newluhux.github.io"
  - name: "小泠酱"
    avatar: "/images/rin.jpg" #欸？图呢
  - name: "Aleksana"
    avatar: "https://portrait.gitee.com/uploads/avatars/user/2180/6541054_aleksana_1649149715.png!avatar200"
  - name: "Dram"
    link: "https://dram.page/"
    bio: "dramforever"
    avatar: "https://rp.ydz1.gq/https://avatars.githubusercontent.com/u/2818072"
  - name: "Hykilpikonna"
    avatar: "https://rp.ydz1.gq/https://avatars.githubusercontent.com/u/22280294"
  - name: "纱月酱"
    link: "https://sbchild.top"
    bio: ""
    avatar: "https://rp.ydz1.gq/https://avatars.githubusercontent.com/u/55868015"
  - name: "Lanta"
    bio: ""
    link: "https://lanta.cyou"
    avatar: "https://rp.ydz1.gq/https://avatars.githubusercontent.com/u/95084339"
  - name: "Chi_Tang"
    bio: "池塘"
    link: "https://chitang.tech"
    avatar: "https://rp.ydz1.gq/https://avatars.githubusercontent.com/u/59324836"
  - name: "Yinfeng"
    link: "https://blog.linyinfeng.com"
    avatar: "https://rp.ydz1.gq/https://avatars.githubusercontent.com/u/11229748"
  - name : "一刀斩"
    avatar : "https://q1.qlogo.cn/g?b=qq&nk=3526514925&s=640"
    link : "https://blog.yidaozhan.ga/"
  - name: "Billchen"
    avatar: "https://rp.ydz1.gq/https://avatars.githubusercontent.com/u/7758042"
  - name: "Tsingkwai"
    link: "https://ruzhtw.top"
    avatar: "https://rp.ydz1.gq/https://avatars.githubusercontent.com/u/38799701"
  - name : "William"
    avatar: "https://rp.ydz1.gq/https://avatars.githubusercontent.com/u/61577379?s=100&v=4"
  - name : "BearChild"
    bio : "背地里连只猫都没有"
    link : "https://imbearchild.cyou/"
    avatar: "https://rp.ydz1.gq/https://imbearchild.cyou/wp-content/uploads/2021/11/paper-cut.webp"
  - name: "Anillc"
    bio: "ani://c"
    avatar: "https://gravatar.loli.net/avatar/5df946d48b36e6f8061cdfe7ebcdf75c?s=200"
    link: "https://ani.llc/"
  - name: "雪沢 坊洛"
    avatar: "https://fangluo.top/static/avatar.png"
    link: "https://fangluo.top/"
    bio: "是可爱的坊洛酱~"
  - name: "十七年蝉"
    avatar: "https://rp.ydz1.gq/https://avatars.githubusercontent.com/u/86961676?v=4"
  - name: "Virginia Senioria"
    bio: "维尔希妮娅"
    link: "https://91khr.github.io"
    avatar: "https://rp.ydz1.gq/https://avatars.githubusercontent.com/u/24869594?v=4"
  - name: "Lneylan"
    bio: "https://rp.ydz1.gq/https://avatars.githubusercontent.com/u/92664048?v=4"
    link: "https://lneylan.com"
  verify: false # 验证每个友链的可访问性，炸了会有提示
  

